### PR TITLE
add kube component attributes

### PR DESCRIPTION
**Pull request by yangcao77**
Signed-off-by: Stephanie <yangcao@redhat.com>

add default configuration for app studio

### CODE REVIEW

**Comment by yangcao77** [comment]
@BethGriggs Would you mind helping review & merge this PR? Thanks.

**Review by BethGriggs — APPROVED** [review]

**Comment by mhdawson** [comment]
@yangcao77 these seem a bit low to me for a real application. How where they chosen and what is the target audience for the sample dev file. Just the sample app or real applications as well?

**Comment by yangcao77** [comment]
@mhdawson it's just for the sample. we want to keep the values in sample lower, if the value is too high, application studio cluster may have trouble when starting multiple components. in real usage, customer can always modify the configuration to increase the value if they need more resources.

**Comment by yangcao77** [comment]
@BethGriggs Do you mind helping merge this PR if there's no other concerns? I do not have permission to do that.

**Pull request merged**
