### PR TITLE
docs: documenting issue with npm install

### PR DESCRIPTION
**Pull request by pacostas**

### CODE REVIEW

**Review by helio-frota — APPROVED** [review]
Great :+1:

**Review by BethGriggs — COMMENTED** [review]
While useful information, I'm not entirely convinced this information should be exposed to the end users in the example. The intent is to remove the `Dockerfile` all together once the outerloop-deploy no longer needs it.

**Comment by helio-frota** [comment]
>  The intent is to remove the Dockerfile all together once the outerloop-deploy no longer needs it.

We can transform that as an issue :+1:

**Comment by BethGriggs** [comment]
Would be nice to consider https://github.com/nodeshift-starters/devfile-sample/pull/13#pullrequestreview-1068045712 before merging.

**Comment by BethGriggs** [comment]
We should be slower with merging these PRs as it immediately impacts what our users receive in the OpenShift UI.

**Comment by helio-frota** [comment]
> We should be slower with merging these PRs as it immediately impacts what our users receive in the OpenShift UI.

yeah that's correct, sorry about that

**Comment by helio-frota** [comment]
> Would be nice to consider https://github.com/nodeshift-starters/devfile-sample/pull/13#pullrequestreview-1068045712 before merging.

again sorry that wasn't showing on github yet next time will wait a bit more :+1:

**Pull request merged**
